version: '2.2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
  node2:
    environment:
      - PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    links:
      - node1:node1
  node3:
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    links:
      - node2:node2
  node4:
    environment:
      - PEERS=ws://node3:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3004:3001"
    links:
      - node3:node3
  node5:
    environment:
      - PEERS=ws://node4:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3005:3001"
    links:
      - node4:node4
  node6:
    environment:
      - PEERS=ws://node5:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3006:3001"
    links:
      - node5:node5
  node7:
    environment:
      - PEERS=ws://node6:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3007:3001"
    links:
      - node6:node6
  node8:
    environment:
      - PEERS=ws://node7:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3008:3001"
    links:
      - node7:node7
  node9:
    environment:
      - PEERS=ws://node8:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3009:3001"
    links:
      - node8:node8
  node10:
    environment:
      - PEERS=ws://node9:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3010:3001"
    links:
      - node9:node9